// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace PMGameplayTags
{
	/** Input Tags **/
	PROJECT_MORPH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	PROJECT_MORPH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	PROJECT_MORPH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack);//记得改名Action
	PROJECT_MORPH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip_LightSword);
	PROJECT_MORPH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnEquip_LightSword);

	/** Action Tags 招式连段Tag **/
	PROJECT_MORPH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ActionTag);

	/** Player Tags **/
	//记得父层级要改成PM_Player_
	PROJECT_MORPH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PM_Ability_Action);
	
	PROJECT_MORPH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PM_Weapon_LightSword);
	
	PROJECT_MORPH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PM_Event_Equip_LightSword);
	PROJECT_MORPH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PM_Event_UnEquip_LightSword);

	
	PROJECT_MORPH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PM_State_Action);
	PROJECT_MORPH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PM_State_Action_IsMoving);

	/** Enemy Tags **/
	PROJECT_MORPH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PM_Enemy_Weapon);

	PROJECT_MORPH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PM_Enemy_Action);

	PROJECT_MORPH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PM_Enemy_State);
	
	PROJECT_MORPH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PM_Enemy_Event);
	
	
}
